spring:
  application:
    name: consumer
  kafka:
    #    Kafka server ?????? , ??
    bootstrap-servers: localhost:9092
    # ?????
    consumer:
      # ??????Id
      client-id: ${spring.application.name}-consumer
      autoCommitInterval: 1000
      # ????????? ??????????
      auto-offset-reset: latest
      # ?????????
      enable-auto-commit: true
      # ?????Id
      groupId: defaultConsumerGroup
      properties:
        # ????????
        request:
          timeout:
            ms: 40000
        # ????????(??????consumer??????,????rebalance??)
        session:
          timeout:
            ms: 40000
        # ???????????????
        spring:
          json:
            trusted:
              packages: '*'