spring:
  application:
    name: producer
  kafka:
    bootstrap-servers: localhost:9092
    # ?????
    producer:
      # ???????Id
      client-id: ${spring.application.name}-producer
      # ????:??????????????????ack??(??0?1?all/-1)
      acks: 1
      # ????
      batch-size: 16384
      # ????????
      buffer-memory: 33554432
      # Kafka????????????
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # ????
        linger:
          ms: 0
      # ????
      retries: 0